# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: 国宝爱你
url: http://super-summer.github.io
feed: /atom.xml
author_info: <a href="http://super-summer.github.io/">国宝</a>

myblog:
  gavatar: images/2.jpg
  gpname: sunjunchao
  linkedin: http://www.linkedin.com/in/sunjunchao
  github: https://github.com/super-summer
  email: mailto:641525309@qq.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
